#!/usr/bin/env bash

set -e

cd $(dirname $0)/../..
ROOT_DIR="$(pwd)"

rm -rf ${ROOT_DIR}/build/makefile
mkdir -p ${ROOT_DIR}/build/makefile
cd ${ROOT_DIR}/build/makefile

cmake ${ROOT_DIR}/src -G "Unix Makefiles"
make VERBOSE=1