#!/usr/bin/env bash

set -e

cd $(dirname $0)/..
ROOT_DIR="$(pwd)"

rm -rf ${ROOT_DIR}/build/xcode
mkdir -p ${ROOT_DIR}/build/xcode
cd ${ROOT_DIR}/build/xcode

cmake ../.. -G "Xcode"
open myproject.xcodeproj